site_name: Anontech
site_url: https://anontech.io
site_description: Official documentation for the Anontech ViziVault Platform
google_analytics:
  - UA-145420782-2
  - auto
theme:
  name: material
  logo: assets/images/anontech-cropped.png
  favicon: assets/images/favicon.png
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Libraries: libraries.md
  - API Reference:
    - Endpoints: api/endpoints.md
    - User Attributes: api/datapoints.md
    - Entity Attributes: api/entities.md
    - Attribute Definitions: api/attributes.md
    - Tags: api/tags.md
    - Regulations: api/regulations.md
    - Rules: api/rules.md
    - Users: api/users.md
    - Entities: api/entity.md
  - Glossary:
    - Attribute Definition: glossary/attribute-definition.md
    - Tag: glossary/tag.md
    - Attribute: glossary/attribute.md
    - Regulation: glossary/regulation.md
    - Rule: glossary/rule.md
    - Storage Request: glossary/storage-request.md
  - Tutorials:
    - Quickstart: tutorials/quickstart.md
    - Attribute Schemas: tutorials/attribute-schemas.md
    #- Data Sharing: tutorials/datasharing.md
    - Reports: tutorials/reports.md
    - Rules: tutorials/rules.md
    - Search: tutorials/search.md
  - Regulations:
    - GDPR (European Union): https://gdpr-info.eu/chapter-3/
    - CCPA (California): https://oag.ca.gov/privacy/ccpa
    - HIPAA (US medical data): https://www.hhs.gov/hipaa/
    - PCI (credit card information): https://www.pcisecuritystandards.org/
    - FERPA (US): https://www2.ed.gov/policy/gen/guid/fpco/ferpa/
    - COPPA (US): https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy
  - ViziVault Enterprise:
      - Overview: vizivault-enterprise/overview.md
      - Dashboard: vizivault-enterprise/dashboard.md
      - Discover: vizivault-enterprise/discover.md
      - Applications: vizivault-enterprise/applications.md
      - Attributes: vizivault-enterprise/attributes.md
      - Tags: vizivault-enterprise/tags.md
      #- Data Sharing: vizivault-enterprise/data-sharing.md
      - Regulations: vizivault-enterprise/regulations.md
      - Reports: vizivault-enterprise/reports.md
      #- Vault: vizivault-enterprise/vault.md
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/libraries.js
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
