site_name: Anontech
site_url: https://anontech.io
site_description: Official documentation for the Anontech ViziVault Platform
google_analytics:
  - UA-145420782-2
  - auto
theme:
  name: material
  logo: assets/images/anontech-cropped.png
  favicon: assets/images/favicon.png
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Libraries: libraries.md
  - API Reference:
    - Endpoints: api/endpoints.md
    - Attributes: api/attributes.md
    - Categories: api/categories.md
    - Datapoints: api/datapoints.md
    - Regulations: api/regulations.md
  - Glossary:
    - Attribute: glossary/attribute.md
    - Category: glossary/category.md
    - Datapoint: glossary/datapoint.md
    - Regulation: glossary/regulation.md
    - Storage Request: glossary/storage-request.md
  - Tutorials:
    - Attribute Schemas: tutorials/attribute-schemas.md
    - Data Sharing: tutorials/datasharing.md
    - Regulation Rules: tutorials/regulation-rules.md
    - Reports: tutorials/reports.md
    - Search: tutorials/search.md
  - Regulations:
    - GDPR (European Union): https://gdpr-info.eu/chapter-3/
    - CCPA (California): https://oag.ca.gov/privacy/ccpa
  - ViziVault Enterprise:
      - Overview: vizivault-enterprise/overview.md
      - Dashboard: vizivault-enterprise/dashboard.md
      - Discovery: vizivault-enterprise/discover.md
      - Applications: vizivault-enterprise/applications.md
      - Attributes: vizivault-enterprise/attributes.md
      - Categories: vizivault-enterprise/categories.md
      - Data Sharing: vizivault-enterprise/data-sharing.md
      - Regulations: vizivault-enterprise/regulations.md
      - Reports: vizivault-enterprise/reports.md
      - Vault: vizivault-enterprise/vault.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
