site_name: Anontech
theme:
  name: material
  logo: assets/images/anontech.png
  favicon: assets/images/favicon.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
